### ISSUE TITLE
Crv to face node error

### ISSUE THREAD

**Issue by Emilien-Etadam** [j8sr0230/Nodes#102]
I dont understand how this node is working : 
![QQ044ptYZN](https://user-images.githubusercontent.com/56485277/204814075-e1e6f591-bf12-48ad-b3bf-3b076fbf1175.jpg)

**Comment by Emilien-Etadam** [comment]
I've tried the fix on my fork and it's working fine now ! Thanks, @FlachyJoe

**Comment by Emilien-Etadam** [comment]
This node is not working as I expected : 
I expected :
![lFO3eK8PwT](https://user-images.githubusercontent.com/56485277/205621651-ade216d6-2bb4-4c45-8bfd-ce1e76c38c8f.jpg)
I get : 
![ijHxBwnJyz](https://user-images.githubusercontent.com/56485277/205621661-a07a2242-d1ea-40ad-8b5e-b19f458496f3.jpg)

It's not the same process as grasshopper ?

**Comment by FlachyJoe** [comment]
@Emilien-Etadam Crv to Face results in two faces, it needs a not-yet-existent Merge node to combine the two curves in a unique one.

**Comment by Emilien-Etadam** [comment]
Ok can't wait for it ! 👍

**Comment by j8sr0230** [comment]
I put the Boundary Surface node on my list ;)
