### ISSUE TITLE
Documentaton Update

### ISSUE THREAD

**Issue by StripeyType** [j8sr0230/Nodes#103]
I feel like a doofus for asking this, but how do I use/open the 'nodes window' or 'scene graph'? I really love what i see here, but on a fresh installation (FlatPak) of 0.21, with the Nodes workbench also installed, it is not clear to me either from the interface or from the docs how I may use this?

**Comment by Emilien-Etadam** [comment]
![ApplicationFrameHost_lbMdCnhjEN](https://user-images.githubusercontent.com/56485277/204868802-965066b0-3981-4ad8-9b4d-4ebd8b0451ef.gif)

**Comment by StripeyType** [comment]
OK, Merci - this is some other problem I am having, clearly. That icon does not exist for me when I switch to the Nodes WB.
I'll blow away this FlatPak installation and try again.

**Comment by StripeyType** [comment]
Oof. Reopening, but I don't think it-s a Nodes workbench issue: I'm getting an error messages that qtpy is not installed. It *is*, but it doesn't appear to be part of the FlatPak, which I think is the source of my problem.
@Emilien-Etadam I'm very sorry to trouble you further, but may I ask how your copy of FreeCAD 0.21 is installed on your system?

**Comment by Emilien-Etadam** [comment]
I am on windows (no choice as a solidworks user), but I will check on POP os tonight

**Comment by StripeyType** [comment]
Thanks so very much! And more than that, thank you so much for your awesome icon contributions! I looks forward to using them. :D

**Comment by j8sr0230** [comment]
Thanks for your report! Could you give us feedback if the issue persists without FlatPak?

**Comment by Emilien-Etadam** [comment]
@StripeyType I ve tried on POPos (Ubuntu) with FlatPak and I cant even load the addons list to install nodes workbench.

**Comment by StripeyType** [comment]
On Ubuntu 22.04LTS, the weekly AppImage seems better behaved; when installing the WB, the Addon Manager complains about qtpy and then helpfully offers to install it...

aaaaand BOOM goes the dynamite. :D

This is definitely a FlatPak issue, rather than an issue with the WB specifically.
