### ISSUE TITLE
Round number

### ISSUE THREAD

**Issue by Emilien-Etadam** [j8sr0230/Nodes#119]
![freecad_uyXJboBFfT](https://user-images.githubusercontent.com/56485277/206206470-346e7d97-e160-432b-ae7c-bcecfb3c5738.gif)

I m starting to play with the nodes but I'm stuck on a problem, I cant round a number to avoid this : 
![t0YVQtJir5](https://user-images.githubusercontent.com/56485277/206206439-4d5da0a6-3aff-433f-ac3a-f92a741c0079.jpg)

**Comment by FlachyJoe** [comment]
Hi,
the required math functions can be done with a PyScript node (Keep in mind In and Out are lists).
![Capture d’écran_2022-12-08_20-48-59](https://user-images.githubusercontent.com/10371513/206553558-3d630207-5dd3-4d52-bef1-cbacd84259d3.png)

**Comment by Emilien-Etadam** [comment]
Ok now I see how it's works. Thanks.
