### ISSUE TITLE
Bug: Doesn't seem to update?

### ISSUE THREAD

**Issue by MisterMakerNL** [j8sr0230/Nodes#82]
I tried it out and I got it to work some what, but it didn't want to update and had to re-open the file to update.
Also tried link daily with no luck!
[nodes.zip](https://github.com/j8sr0230/Nodes/files/9955022/nodes.zip)
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.21.30716 (Git)
Build type: Release
Branch: master
Hash: cbd19631428f1d9eb4faae30220551608a648589
Python 3.10.6, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods: 
  * Assembly3 0.11.3
  * Behave-Dark-Colors 0.1.1
  * BIM 2021.12.0 (Disabled)
  * Dracula 0.0.2
  * ExtremeProDark 2.5.3
  * ExtremeProDark.backup1665346471.659064 2.3.1 (Disabled)
  * ExtremeProLight 1.3.3
  * ExtremeProLight.backup1665559197.7999926
  * FeedsAndSpeeds 0.5.0
  * FEM_FrontISTR 0.1.0
  * IconThemes
  * lattice2 1.0.0
  * Nodes 0.1.0
  * PieMenu 1.1.16
  * PieMenu.backup1664822562.2342157
  * ProDarkThemePreferencePack 1.0.0
  * scanObjects
  * SelectorToolbar
  * sheetmetal 0.2.58
  * SP_Startup
  * ToolbarStyle
[/code]

**Comment by j8sr0230** [comment]
I had forgotten to increase the version of FreeCAD Nodes in the Package.xml. Now the update should not cause any problems or? In case of doubt just delete the addon and reinstall it.
