### ISSUE TITLE
Nodes Icons

### ISSUE THREAD

**Issue by Emilien-Etadam** [j8sr0230/Nodes#83]
Hi, 
I can help to put an icon for each node (reuse existing one from freecad or create a new one) let me know if this is needed.

I am an advanced user of Solidworks and Grasshopper so I following this Addon with a lot of hope. 
I am not a programmer but I would like to help.

Thanks.

**Comment by luzpaz** [comment]
@j8sr0230 bump

**Comment by j8sr0230** [comment]
@Emilien-Etadam @luzpaz Sorry it took me so long to reply, but job, family, kids etc .... :) Great that you would like to contribute to my project. You don't have to be a programmer to support me (by the way, I am "only" a mechanical engineer)! 

The context menu for creating new nodes can be accessed by right-clicking in the scene graph. In this menu, each node should have its own icon. Currently, the same icon is displayed as a placeholder for each node. You are welcome to contribute to inserting or creating the node icons. For this purpose, we should always adopt the icon corresponding to the FreeCAD function if it already exists (see [FreeCAD Artwork](https://wiki.freecadweb.org/Artwork)). If none exists yet, you can let your creativity run wild. Please keep in mind that the icons should work with both dark and light FreeCAD style sheets. You could also use Grasshopper 3D, Sverchock or Geometry Nodes as template.

![freecad_nodes_icon_manual](https://user-images.githubusercontent.com/39261150/202193590-564771c5-0dc5-4f91-a36b-c95e37b979e6.png)

To contribute, copy your new icon (32x32) into the icons folder (1) and link to it in the source code of the desired node (2, 3). If everything works in your fork, create a pull request and I'll take care of the merging.

I hope that was understandable. If you still have questions, just contact me. Welcome to the team and have fun helping to create FreeCAD Nodes icons :)

**Comment by Emilien-Etadam** [comment]
![JA9Zj4mwt9](https://user-images.githubusercontent.com/56485277/202266195-5c104d91-4a5b-4c3b-abdc-e9f243ba1852.jpg)

It works !

**Comment by j8sr0230** [comment]
Great, immediately looks more professional ;)

**Comment by Emilien-Etadam** [comment]
![W2fD4wKV93](https://user-images.githubusercontent.com/56485277/202268017-19e5bec4-4f1e-43eb-ae08-81f917400939.jpg)

Yep !

**Comment by Emilien-Etadam** [comment]
![vw8CpunhuZ](https://user-images.githubusercontent.com/56485277/202268345-7e8a9328-fe0c-4787-ad35-51aa1afdb378.jpg)

**Comment by j8sr0230** [comment]
Thanks for the support, looks really great!

**Comment by Emilien-Etadam** [comment]
![60OSiPhBBP](https://user-images.githubusercontent.com/56485277/202693577-24e03a1a-8b1d-4dde-a27a-eda567974b15.jpg)
 4 New Icons

**Comment by luzpaz** [comment]
FANTASTIC!!!

**Comment by Emilien-Etadam** [comment]
> 

Ok let me check how to do this the right way...

**Comment by Emilien-Etadam** [comment]
![Deq1CCY3LH](https://user-images.githubusercontent.com/56485277/203128976-3a3dc493-1dc8-4e06-92e8-2897d4860888.jpg)
4 New Icons

**Comment by luzpaz** [comment]
CC @mistermakernl (just a heads up that this is happening and you might like to keep it on your radar)

**Comment by j8sr0230** [comment]
Wow, your designs are really great. The Voronoi on Srf icon is better than the one from Grasshopper;) I'm still busy today, but tomorrow I will merge the current pulls. Thanks a lot already!!!

**Comment by j8sr0230** [comment]
@luzpaz do you mean the Import Step node?

**Comment by MisterMakerNL** [comment]
I made some icons myself:
https://mistermaker.gumroad.com/l/Linkstage_Icons
I also used Grasshopper couple of months ago for a job, and I use Sverchok and other nodes in Blender. So surely I watch this :)

**Comment by j8sr0230** [comment]
@Emilien-Etadam Congratulations, your new icons are online :) Thanks for your efforts!

**Comment by Emilien-Etadam** [comment]
Great ! It's only the beginning !

**Comment by Emilien-Etadam** [comment]
![BRVq34FC12](https://user-images.githubusercontent.com/56485277/203976612-8ac62519-1bb7-4f4c-b36f-56e98ac7e8ac.jpg)

Do you prefer I Pull each time or wait for more icons ?

**Comment by j8sr0230** [comment]
Once again a great design :) I think it's enough if you make a pull every 4 to 5 icons. By the way, do you already know our FreeCAD Nodes topic in the forum? There I always publish the newest nodes. You can find it here: [https://forum.freecadweb.org/viewtopic.php?f=24&t=71651&start=50](https://forum.freecadweb.org/viewtopic.php?f=24&t=71651&start=50).

**Comment by luzpaz** [comment]
@Emilien-Etadam would be great to see a PR for your work :stuck_out_tongue_winking_eye:

**Comment by Emilien-Etadam** [comment]
@j8sr0230  Yes I keep an eye on the topic, thanks.
@luzpaz  I will PR (pull request ?) every 4 icons.

**Comment by luzpaz** [comment]
@Emilien-Etadam Yea, no worries. We all went through our git learning phase (I still am :rofl:). 

What you can do is reference this PR with each PR you make by adding this PR number `#83` to the commit summary. When you're ready to close this PR you can add `Fixes #83` to the commit summary and it will automatically close when your PR is merged.

**Comment by Emilien-Etadam** [comment]
@luzpaz  I don't understand anything, sorry...  why I should do this ?

**Comment by Emilien-Etadam** [comment]
![DOJWGAYh1i](https://user-images.githubusercontent.com/56485277/204613578-e2146317-5963-4884-8564-0881cce3b551.jpg)
New Icons

**Comment by luzpaz** [comment]
@Emilien-Etadam See https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by Emilien-Etadam** [comment]
@luzpaz I can't do this : 
![rg3AKglFQ7](https://user-images.githubusercontent.com/56485277/204755126-f3c0b33b-ba3e-4643-bb29-bf8ef9f29ac1.jpg)

**Comment by luzpaz** [comment]
You're not. I didn't clarify myself enough. 

Make a PR and in the summary just mention this issue by it's number preceded with a hashtag like this:  `#83` (without the formatting of course, it's enabled for emphasis here). This will notate this issue (the one we are discussing at this moment) and reference that the commit you made is linked to this ticket. When the time comes that you want to close this ticket, you can do so by making a PR that has `Fixes #83` in the commit summary. In turn, when it is merged, this issue will automatically close. 

Does that make sense? (Sorry if I complicated things for you.)

**Comment by Emilien-Etadam** [comment]
@j8sr0230  Why did you removed the icons here ?
![C916uasqLw](https://user-images.githubusercontent.com/56485277/205694291-33696d50-94c0-424d-9cec-e6e08d35ec90.jpg)

**Comment by j8sr0230** [comment]
I was not sure from the beginning if the many icons would overload the node graph.  Basically I aim for a clean clear layout like Blenders Geometry Nodes editor, but would let the community change my mind :)
